### ISSUE TITLE
"tegrastats was not found at the expected location ~/tegrastats"

### ISSUE THREAD

**Issue by MBoaretto25** [martinkersner/gtop#9]
Where can I change tegrastats location?

**Comment by phaabe** [comment]
why is that closed? What's the solution? Just installed gtop and I have the same issue :-)

**Comment by harshilpatel312** [comment]
@phaabe 
1. Run `which tegrastats` in a shell and find the location of your tegrastats executable. For me, its `/usr/bin/tegrastats`.
2. Open `gtop.hh` and set `TEGRASTATS_PATH` to the path found in 1.

**Comment by SaddamBInSyed** [comment]
> @phaabe
> 
> 1. Run `which tegrastats` in a shell and find the location of your tegrastats executable. For me, its `/usr/bin/tegrastats`.
> 2. Open `gtop.hh` and set `TEGRASTATS_PATH` to the path found in 1.

followed carefully the mentioned steps but the same error still.

**Comment by devfox-se** [comment]
I think this error is still actual. I have replaced ~/tegrastats to /usr/bin/tegrastats but after running gtop I get an error
```
> terminate called after throwing an instance of 'std::out_of_range'
> what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
> Aborted
```

**Comment by burak-yildizoz** [comment]
This issue should not be closed. I get the same error as @devfox-se on Jetson TX2.
